[app]
id   = "SPAMMER"
name = "SPAMMER"

[screens]
playfield = { service = "front-screen", port = 80 }
backglass = { service = "back-screen", port = 80 }
dmd       = { service = "dmd-screen", port = 80 }

[compose]
file = "deploy/docker-compose.yml"
